### ISSUE TITLE
[FEAT]: Vim Plugin Support

### ISSUE THREAD

**Issue by KrazyKirby99999** [typesplainer/typesplainer#4]
### Description

A vim plugin of this tool would be very useful.

### Additional Information

https://github.com/vim/vim

**Comment by wasi-master** [comment]
Thanks for the suggestion, I'll try. It may take a while since I do not use vim.

**Comment by wasi-master** [comment]
So vim uses a language called vim script? I want to add it but I need some help with that. Since you're already using vim you're probably much more experienced on it than me. So can you or someone else give it a try? It's really simple, just call `python -m typesplainer PATH_TO_FILE --json` and it will return a JSON output, parse the JSON, show it to the user, Maybe save it in a cache if you want. Also, the python executable name may be different so a setting to customize it would be nice

**Comment by KrazyKirby99999** [comment]
Vim uses vimscript. I haven't made any vim plugins before, but I'll do what I can.

**Comment by KrazyKirby99999** [comment]
I created the plugin - https://github.com/KrazyKirby99999/vim-typesplainer

**Comment by wasi-master** [comment]
@KrazyKirby99999 that's awesome. I've created a @typesplainer organization for easier management for typesplainer extensions and tools. Would you like to be part of it and continue development there if you want?

**Comment by KrazyKirby99999** [comment]
Sure, I would be glad to.

**Comment by wasi-master** [comment]
Thanks @KrazyKirby99999 , also maybe publish this extension to the [vimawesome](https://vimawesome.com/submit) website?
